const LANGUAGE_NAMES: Record<string, string> = {
  tur: "Türkçe",
  tr: "Türkçe",
  eng: "İngilizce",
  en: "İngilizce",
  ger: "Almanca",
  deu: "Almanca",
  de: "Almanca",
  fre: "Fransızca",
  fra: "Fransızca",
  fr: "Fransızca",
  spa: "İspanyolca",
  es: "İspanyolca",
  ita: "İtalyanca",
  it: "İtalyanca",
  rus: "Rusça",
  ru: "Rusça",
  ara: "Arapça",
  ar: "Arapça",
  jpn: "Japonca",
  ja: "Japonca",
  kor: "Korece",
  ko: "Korece",
  chi: "Çince",
  zho: "Çince",
  zh: "Çince",
  por: "Portekizce",
  pt: "Portekizce",
  nld: "Felemenkçe",
  dut: "Felemenkçe",
  nl: "Felemenkçe",
  pol: "Lehçe",
  pl: "Lehçe",
  swe: "İsveççe",
  sv: "İsveççe",
  nor: "Norveççe",
  no: "Norveççe",
  dan: "Danca",
  da: "Danca",
  fin: "Fince",
  fi: "Fince",
  ell: "Yunanca",
  gre: "Yunanca",
  el: "Yunanca",
  heb: "İbranice",
  he: "İbranice",
  hin: "Hintçe",
  hi: "Hintçe",
  fas: "Farsça",
  per: "Farsça",
  fa: "Farsça",
  ukr: "Ukraynaca",
  uk: "Ukraynaca",
  ron: "Rumence",
  rum: "Rumence",
  ro: "Rumence",
  bul: "Bulgarca",
  bg: "Bulgarca",
  hun: "Macarca",
  hu: "Macarca",
  ces: "Çekçe",
  cze: "Çekçe",
  cs: "Çekçe",
  srp: "Sırpça",
  sr: "Sırpça",
  hrv: "Hırvatça",
  hr: "Hırvatça",
  aze: "Azerice",
  az: "Azerice",
  kur: "Kürtçe",
  ku: "Kürtçe",
  und: "Belirtilmemiş",
  mul: "Çoklu dil",
};

export function languageName(code: string | null): string | null {
  if (!code) return null;
  const key = code.toLowerCase();
  return LANGUAGE_NAMES[key] ?? code.toUpperCase();
}
